### ISSUE TITLE
Make master compile

### ISSUE THREAD

**Issue by heatsink** [mobileappdevhm/dev-team-1-cie-app-in-flutter#164]
There is currently an error where it wont compile on my iphone simulator

**Comment by heatsink** [comment]
Stacktrace:
Launching lib/main.dart on iPhone 7 in debug mode...
compiler message: Unhandled exception:
Crash when compiling file:///Users/sean/workspace/dev-1/dev-team-1-cie-app-in-flutter/lib/widgets/courseDetails.dart,
at character offset 2438:
lib/widgets/courseDetails.dart: Internal problem: Unhandled this in defaultTreeNode.
#0      internalProblem (package:front_end/src/fasta/problems.dart:30)
#1      unhandled (package:front_end/src/fasta/problems.dart:43)
#2      ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:112)
#3      TreeVisitor.defaultExpression (package:kernel/visitor.dart:140)
#4      TreeVisitor.visitThisExpression (package:kernel/visitor.dart:171)
#5      ThisExpression.accept (package:kernel/ast.dart:3341)
#6      ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287)
#7      PropertyGet.accept (package:kernel/ast.dart:2242)
#8      ConstnessEvaluator.visitMethodInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:198)
#9      MethodInvocation.accept (package:kernel/ast.dart:2820)
#10     ConstnessEvaluator.visitMethodInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:203)
#11     MethodInvocation.accept (package:kernel/ast.dart:2820)
#12     ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:169)
#13     ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#14     ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99)
#15     evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466)
#16     BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710)
#17     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697)
#18     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684)
#19     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
#20     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565)
#21     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530)
#22     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796)
#23     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670)
#24     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467)
#25     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
#26     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659)
#27     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535)
#28     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451)
#29     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335)
#30     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198)
<asynchronous suspension>
#31     Loader.buildBodies (package:front_end/src/fasta/loader.dart:157)
<asynchronous suspension>
#32     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292)
<asynchronous suspension>
#33     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140)
<asynchronous suspension>
#34     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
#35     _rootRun (dart:async/zone.dart:1126)
#36     _CustomZone.run (dart:async/zone.dart:1023)
#37     runZoned (dart:async/zone.dart:1501)
#38     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
#39     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61)
<asynchronous suspension>
#40     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
<asynchronous suspension>
#41     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:254)
#42     new Future.<anonymous closure> (dart:async/future.dart:174)
#43     _rootRun (dart:async/zone.dart:1122)
#44     _CustomZone.run (dart:async/zone.dart:1023)
#45     _CustomZone.runGuarded (dart:async/zone.dart:925)
#46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#47     _rootRun (dart:async/zone.dart:1126)
#48     _CustomZone.run (dart:async/zone.dart:1023)
#49     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#50     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#51     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#52     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)


#0      internalProblem (package:front_end/src/fasta/problems.dart:30)
#1      unhandled (package:front_end/src/fasta/problems.dart:43)
#2      ConstnessEvaluator.defaultTreeNode (package:front_end/src/fasta/kernel/constness_evaluator.dart:112)
#3      TreeVisitor.defaultExpression (package:kernel/visitor.dart:140)
#4      TreeVisitor.visitThisExpression (package:kernel/visitor.dart:171)
#5      ThisExpression.accept (package:kernel/ast.dart:3341)
#6      ConstnessEvaluator.visitPropertyGet (package:front_end/src/fasta/kernel/constness_evaluator.dart:287)
#7      PropertyGet.accept (package:kernel/ast.dart:2242)
#8      ConstnessEvaluator.visitMethodInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:198)
#9      MethodInvocation.accept (package:kernel/ast.dart:2820)
#10     ConstnessEvaluator.visitMethodInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:203)
#11     MethodInvocation.accept (package:kernel/ast.dart:2820)
#12     ConstnessEvaluator.visitConstructorInvocation (package:front_end/src/fasta/kernel/constness_evaluator.dart:169)
#13     ConstructorInvocation.accept (package:kernel/ast.dart:2983)
#14     ConstnessEvaluator.evaluate (package:front_end/src/fasta/kernel/constness_evaluator.dart:99)
#15     evaluateConstness (package:front_end/src/fasta/kernel/constness_evaluator.dart:466)
#16     BodyBuilder.inferConstness (package:front_end/src/fasta/kernel/body_builder.dart:710)
#17     BodyBuilder.finishFunction (package:front_end/src/fasta/kernel/body_builder.dart:697)
#18     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:684)
#19     DietListener.parseFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:718)
#20     DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:565)
#21     DietListener.endMethod (package:front_end/src/fasta/source/diet_listener.dart:530)
#22     Parser.parseMethod (package:front_end/src/fasta/parser/parser.dart:3796)
#23     Parser.parseClassMemberImpl (package:front_end/src/fasta/parser/parser.dart:3670)
#24     Parser.parseClassBody (package:front_end/src/fasta/parser/parser.dart:3467)
#25     Parser.parseClass (package:front_end/src/fasta/parser/parser.dart:1699)
#26     Parser.parseClassOrNamedMixinApplication (package:front_end/src/fasta/parser/parser.dart:1659)
#27     Parser.parseTopLevelKeywordDeclaration (package:front_end/src/fasta/parser/parser.dart:535)
#28     Parser.parseTopLevelDeclarationImpl (package:front_end/src/fasta/parser/parser.dart:451)
#29     Parser.parseUnit (package:front_end/src/fasta/parser/parser.dart:335)
#30     SourceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:198)
<asynchronous suspension>
#31     Loader.buildBodies (package:front_end/src/fasta/loader.dart:157)
<asynchronous suspension>
#32     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:292)
<asynchronous suspension>
#33     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:140)
<asynchronous suspension>
#34     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:105)
#35     _rootRun (dart:async/zone.dart:1126)
#36     _CustomZone.run (dart:async/zone.dart:1023)
#37     runZoned (dart:async/zone.dart:1501)
#38     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:105)
#39     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:61)
<asynchronous suspension>
#40     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:33)
<asynchronous suspension>
#41     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:254)
#42     new Future.<anonymous closure> (dart:async/future.dart:174)
#43     _rootRun (dart:async/zone.dart:1122)
#44     _CustomZone.run (dart:async/zone.dart:1023)
#45     _CustomZone.runGuarded (dart:async/zone.dart:925)
#46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965)
#47     _rootRun (dart:async/zone.dart:1126)
#48     _CustomZone.run (dart:async/zone.dart:1023)
#49     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949)
#50     Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#51     _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#52     _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#53     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)

Compiler terminated unexpectedly on lib/main.dart
Error launching application on iPhone 7.

**Comment by heatsink** [comment]
Update: This isn't exclusive to the iOS simulator, the master code is unable to load for real iOS devices as well.

**Comment by heatsink** [comment]
merged.
